services:
  - type: web
    name: porra-mundial-2026
    runtime: python
    buildCommand: pip install uv && uv sync
    startCommand: uv run uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.13"
